apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: freshpod-dev
  namespace: kube-system
  labels:
    k8s-app: freshpod
    tier: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: freshpod
      tier: dev
  template:
    metadata:
      labels:
        k8s-app: freshpod
        tier: dev
    spec:
      containers:
      - name: freshpod
        image: freshpod:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          type: Socket
          path: /var/run/docker.sock
      terminationGracePeriodSeconds: 1
