apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: freshpod
  namespace: kube-system
  labels:
    k8s-app: freshpod
    tier: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: freshpod
      tier: prod
  template:
    metadata:
      labels:
        k8s-app: freshpod
        tier: prod
    spec:
      containers:
      - name: freshpod
        image: gcr.io/ahmetb-public/freshpod:e12d40c
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          type: Socket
          path: /var/run/docker.sock
      terminationGracePeriodSeconds: 1
