apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: freshpod
  namespace: kube-system
  labels:
    app: freshpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshpod
  template:
    metadata:
      labels:
        app: freshpod
    spec:
      containers:
      - name: freshpod
        image: freshpod:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          type: Socket
          path: /var/run/docker.sock
      terminationGracePeriodSeconds: 1
